<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Inventories</name>
   <tag></tag>
   <elementGuidId>6f3c6ec3-52d0-4723-a9f8-34ae03c9f25e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[normalize-space()='Inventories']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
