<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Engagements_1</name>
   <tag></tag>
   <elementGuidId>f3240be8-494b-4a13-9ce5-b2e7881f31ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ad9e86d5ee78-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ad9e86d5ee78-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f9883b3-5e06-40e3-8118-34c58a6fa762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>b93abff8-0067-4eba-bb6a-c9c3cfc17a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d032d6ca-f504-4a10-8b68-d51b00c78f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60bce601-17d1-49f8-b9c3-d65c8b0c3e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad9e86d5ee78-0</value>
      <webElementGuid>7a08bd76-7229-40e1-9a53-15e22d38e152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Engagements</value>
      <webElementGuid>822d82c8-3780-42b8-b840-0bc76640e044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad9e86d5ee78-0&quot;)</value>
      <webElementGuid>124e664a-5e80-4b01-972f-48ec5475c916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ad9e86d5ee78-0']</value>
      <webElementGuid>6e1a0513-6946-49b6-ba34-2d68ff3f736b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ad9e86d5ee78']/div/div[2]/div</value>
      <webElementGuid>055bcaee-25f0-48ff-994e-9c4218e05803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checklists'])[1]/following::div[5]</value>
      <webElementGuid>7ed65c52-7bc3-470f-9101-1594d4ebee08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[2]/following::div[10]</value>
      <webElementGuid>b9e34e91-2300-4778-ad91-059a6108ae26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Letters'])[1]/preceding::div[1]</value>
      <webElementGuid>44722316-30cb-4119-8ea1-ab4fdd7ca008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>4f2f9cd5-21bf-4b2b-a230-1992776150a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ad9e86d5ee78-0' and (text() = 'Engagements' or . = 'Engagements')]</value>
      <webElementGuid>68d8e48e-e67d-4bf1-a603-d5278db1a85c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
