<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_check_boxMultiple Choice</name>
   <tag></tag>
   <elementGuidId>458945f7-33bb-4add-b033-85c5c28f1562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ab433e6e4f12-5 > div.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ab433e6e4f12-5']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75af3daf-f207-4471-9d04-64ed057c366a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>cc7a4e23-1708-48d9-ba01-f6ddb919694d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>check_boxMultiple Choice</value>
      <webElementGuid>18f4a6a7-4055-423b-9ff0-431d8d26855c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab433e6e4f12-5&quot;)/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>36cb30d9-abd1-4060-bdd6-83a54b4f884a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ab433e6e4f12-5']/div</value>
      <webElementGuid>7fbdb377-f314-4510-8830-7075342392fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='short_text'])[2]/following::div[2]</value>
      <webElementGuid>344c6379-f18e-41f7-bce5-895f856ffe88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a follow-up question'])[1]/preceding::div[67]</value>
      <webElementGuid>a3b5b44d-7adf-4174-b08c-44fa366a4438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Multiple Choice']/parent::*</value>
      <webElementGuid>594c05f9-78fa-4878-ba37-6875b2445a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>c2769edc-fdb8-4f0f-b8e9-5bc6eaf79814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'check_boxMultiple Choice' or . = 'check_boxMultiple Choice')]</value>
      <webElementGuid>a445e79b-85c0-4059-862a-9793859eb08c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
