<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_eventDate</name>
   <tag></tag>
   <elementGuidId>bfafac99-c443-414c-bf2f-6b4ce292a62c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a88563dc886e-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a88563dc886e-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2fa4bfbd-62b6-4c35-8344-a06c9cfbe1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>7d1928d7-50a2-45c0-bf99-db5d1c05b872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e3dde59a-6f80-4699-9f85-7048e877f0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cbaccac4-eec9-44a0-aa34-4ef1eced644b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a88563dc886e-0</value>
      <webElementGuid>a59a54de-1e37-4ecc-ba77-a5c0bb11aedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>eventDate</value>
      <webElementGuid>39347531-4039-45e7-b960-79133662f1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a88563dc886e-0&quot;)</value>
      <webElementGuid>b7432fbd-7e52-4921-9b42-1f3896b37b49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a88563dc886e-0']</value>
      <webElementGuid>cdd50a9a-83a0-46ad-9960-c36fc5128f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a88563dc886e']/div/div[2]/div</value>
      <webElementGuid>e10952d5-c4d7-433d-804d-6b22ee88af06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='notes'])[1]/following::div[5]</value>
      <webElementGuid>96d4c273-cd96-4952-8a59-68efc3484105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>acf830b7-0ca0-40ba-bc85-aed6d41f9160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a88563dc886e-0' and (text() = 'eventDate' or . = 'eventDate')]</value>
      <webElementGuid>1dd02db6-5275-446d-8514-e8cee058c51a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
