<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_notesLong Answer</name>
   <tag></tag>
   <elementGuidId>8de05027-42c9-442f-8043-9c6fa0b53c1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a5e1c3df35ae-1 > div.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a5e1c3df35ae-1']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9edda912-f0ad-4405-9f37-944643a24b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>b4b8280e-3033-45f0-8612-abfc47679561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>notesLong Answer</value>
      <webElementGuid>e6388690-b575-4073-a37d-737aebc7be12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a5e1c3df35ae-1&quot;)/div[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>abd4ac70-bbc3-42a7-89d1-2c2b7699ecf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a5e1c3df35ae-1']/div</value>
      <webElementGuid>1df0129f-311e-4d3c-ac7e-e46199885952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='event'])[1]/following::div[2]</value>
      <webElementGuid>5c9318b8-9747-4bb7-b2ee-ca195df5190a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Long Answer']/parent::*</value>
      <webElementGuid>dfe7e3cd-6ee8-4578-b04a-d68a227de53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]/div</value>
      <webElementGuid>e85e098c-d015-49b4-8f9b-7395a1ccdfd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'notesLong Answer' or . = 'notesLong Answer')]</value>
      <webElementGuid>dbc3810c-1597-46c8-807b-6d3c1295bd66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
