<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Add_mat-mdc-tooltip-trigger fa-regular fa_48f538_1_2</name>
   <tag></tag>
   <elementGuidId>00cc0ef2-29d3-454f-ad14-160735169ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mat-mdc-tooltip-trigger.fa-regular.fa-message-question.blue-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3097a744-523b-4f31-bab9-262aae8ad16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Add a question</value>
      <webElementGuid>29c4f93f-ae48-4c34-a82f-6fb6c1d32bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-tooltip-trigger fa-regular fa-message-question blue-icons</value>
      <webElementGuid>ddd7eb19-f8a8-4ff7-8a17-b3697c11624d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-ng-1-24</value>
      <webElementGuid>b291d80d-22ce-4e48-8564-c86b517b4ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdk-describedby-host</name>
      <type>Main</type>
      <value>ng-1</value>
      <webElementGuid>265525a2-3366-4a25-95dd-2dc43448d0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main&quot;]/app-templates-dashboard[@class=&quot;ng-star-inserted&quot;]/mat-drawer-container[@class=&quot;mat-drawer-container countable-drawer templates mat-drawer-container-has-open&quot;]/mat-drawer-content[@class=&quot;mat-drawer-content overflow-hidden&quot;]/div[@class=&quot;contant-block-main flex-1 h-100 overflow-x-auto templates-content dashboard-main bg-white p-0 gap-0&quot;]/app-firm-knowledge-of-client[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;checklist-client-knowledge px-24 bg-gray-50&quot;]/div[@class=&quot;checklist-client-knowledge-body&quot;]/div[@class=&quot;checklist-client-knowledge-footer1 mt-20 ng-star-inserted&quot;]/div[@class=&quot;rounded-social-buttons&quot;]/a[@class=&quot;social-button&quot;]/i[@class=&quot;mat-mdc-tooltip-trigger fa-regular fa-message-question blue-icons&quot;]</value>
      <webElementGuid>35759108-9d34-4b06-abb7-076342479755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>289af030-6d48-4f22-a034-489107001c80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
