<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Add_mat-mdc-tooltip-trigger fa-regular fa_fdbc67_1</name>
   <tag></tag>
   <elementGuidId>0879f999-772d-463a-ae83-cfd44f67a4bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mat-mdc-tooltip-trigger.fa-regular.fa-shapes.blue-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>19d87121-5e34-40a8-bc22-92aa7a25de1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltip</name>
      <type>Main</type>
      <value>Category</value>
      <webElementGuid>aaa66133-23c7-4fb9-a4f8-b8608fad4e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-tooltip-trigger fa-regular fa-shapes blue-icons</value>
      <webElementGuid>3c7741cf-82c2-4bf3-9503-b016c02a8dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-ng-1-23</value>
      <webElementGuid>e49d60a3-ca56-4eee-bef0-cf76b15de8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdk-describedby-host</name>
      <type>Main</type>
      <value>ng-1</value>
      <webElementGuid>3fd14b4a-b079-4605-b7ae-60fc569294b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dasboard-container layout-dashboard drawer-small&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;dashboard-main&quot;]/app-templates-dashboard[@class=&quot;ng-star-inserted&quot;]/mat-drawer-container[@class=&quot;mat-drawer-container countable-drawer templates mat-drawer-container-has-open&quot;]/mat-drawer-content[@class=&quot;mat-drawer-content overflow-hidden&quot;]/div[@class=&quot;contant-block-main flex-1 h-100 overflow-x-auto templates-content dashboard-main bg-white p-0 gap-0&quot;]/app-firm-knowledge-of-client[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;checklist-client-knowledge px-24 bg-gray-50&quot;]/div[@class=&quot;checklist-client-knowledge-body&quot;]/div[@class=&quot;checklist-client-knowledge-footer1 mt-20 ng-star-inserted&quot;]/div[@class=&quot;rounded-social-buttons&quot;]/a[@class=&quot;social-button&quot;]/i[@class=&quot;mat-mdc-tooltip-trigger fa-regular fa-shapes blue-icons&quot;]</value>
      <webElementGuid>4b44f1ed-fbd6-41bf-9495-43ae47a1b864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>f73d4ea3-7b96-4d7b-b652-1454d6eb9e70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
