<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(1 checklists)_mat-radio-149-input</name>
   <tag></tag>
   <elementGuidId>dc6cc0a4-9ec6-4a38-b5c5-655fbdab500a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-radio-149-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-radio-149-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcb5ea89-9c84-43f0-94e6-637de95c0de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f2d8fc07-3f5b-46ba-9aba-48ff384ec30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-radio__native-control</value>
      <webElementGuid>272b4339-dac7-4726-a053-c22939bab003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-radio-149-input</value>
      <webElementGuid>d76c88c9-28b3-4c88-aac1-aa988dd477b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8cb75f68-19c0-461f-9f0a-a6c6ef808ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-149-input&quot;)</value>
      <webElementGuid>acf1df22-f333-4a69-b91d-49ed405411bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-radio-149-input']</value>
      <webElementGuid>d0fef637-1a38-4d42-bfbc-e7889bb66e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-149']/div/div/input</value>
      <webElementGuid>597897d6-81aa-444b-b3a7-8da977230402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/mat-radio-button/div/div/input</value>
      <webElementGuid>64716af5-c00b-485e-9ec3-1a6668a7f227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'mat-radio-149-input']</value>
      <webElementGuid>8f15449e-aa07-44c3-8992-e3d8785e1018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
