<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Planning</name>
   <tag></tag>
   <elementGuidId>a467e6f6-89c9-486d-9aa2-2c332c733ea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cdk-accordion-child-361 > div.mat-expansion-panel-body > mat-list.mat-mdc-list.mat-mdc-list-base.mdc-list.templates-list-items > mat-list-item.mat-mdc-list-item.mdc-list-item.mat-mdc-list-item-single-line.mdc-list-item--with-one-line.ng-star-inserted > span.mdc-list-item__content > span.mat-mdc-list-item-unscoped-content.mdc-list-item__primary-text > div.list-item-content > span.item-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@type='button'])[50]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>227e99af-3575-4eb0-b597-d019332efb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-title</value>
      <webElementGuid>46f7e832-caeb-48fc-a8f7-e7de9a00a6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f86ee1ba-05a3-498c-aa49-420d76b38f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Planning</value>
      <webElementGuid>c6a69376-8cd0-410e-bd6a-6f101351a9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-361&quot;)/div[@class=&quot;mat-expansion-panel-body&quot;]/mat-list[@class=&quot;mat-mdc-list mat-mdc-list-base mdc-list templates-list-items&quot;]/mat-list-item[@class=&quot;mat-mdc-list-item mdc-list-item mat-mdc-list-item-single-line mdc-list-item--with-one-line ng-star-inserted&quot;]/span[@class=&quot;mdc-list-item__content&quot;]/span[@class=&quot;mat-mdc-list-item-unscoped-content mdc-list-item__primary-text&quot;]/div[@class=&quot;list-item-content&quot;]/span[@class=&quot;item-title&quot;]</value>
      <webElementGuid>71b7b61d-abac-4a10-8681-bb7ac948abf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@type='button'])[50]</value>
      <webElementGuid>ba3082b4-ba25-4e7d-bd53-d6110a13343c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-361']/div/mat-list/mat-list-item/span/span/div/span[2]</value>
      <webElementGuid>b5a1e44d-58c4-458a-9614-7da27b49e66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PravinTest 0701'])[1]/following::span[5]</value>
      <webElementGuid>1cacb847-d629-4edc-973a-bd2572d76c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Acceptance and Continuance'])[8]/following::span[9]</value>
      <webElementGuid>77ce8ed4-7872-4dd7-b660-fcd4f53d9e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Independence'])[5]/preceding::span[2]</value>
      <webElementGuid>27e5e411-4c91-479b-a777-96a28b4d2b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Acceptance and Continuance'])[9]/preceding::span[6]</value>
      <webElementGuid>50e1ddf2-bb21-4370-a661-50531db58264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[17]/div/div/div/mat-list/mat-list-item/span/span/div/span[2]</value>
      <webElementGuid>fa261dbf-4bff-43c1-9fdb-e18b427d38a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = 'button' and (text() = 'Planning' or . = 'Planning')]</value>
      <webElementGuid>4461d8dc-baf4-4f55-bda7-aeaa9707a71d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
