<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Map Template</name>
   <tag></tag>
   <elementGuidId>13e16465-b045-453d-b626-75f1c55e6497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cdk-drop-list-0']/tbody/tr/td[3]/div/button/span[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f20b0738-18af-4197-aebc-507d5b2a6379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-label</value>
      <webElementGuid>cb7dc4d2-00c1-4072-abe8-be09ffc817c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Map Template</value>
      <webElementGuid>e8400b47-fa75-4e63-a472-b39c4d79d7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-0&quot;)/tbody[@class=&quot;mdc-data-table__content ng-star-inserted&quot;]/tr[@class=&quot;mat-mdc-row mdc-data-table__row cdk-row cdk-drag ng-star-inserted&quot;]/td[@class=&quot;mat-mdc-cell mdc-data-table__cell cdk-cell mtemplate-cell overflow-auto cdk-column-mappedTemplate mat-column-mappedTemplate ng-star-inserted&quot;]/div[@class=&quot;mapped-temp-edit flexbox-row flex-nowrap align-items-center w-100 gap-0&quot;]/button[@class=&quot;button-text ps-24 py-10 mdc-button mat-mdc-button text-error mat-primary mat-mdc-button-base ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/div[@class=&quot;flexbox-row gap-8&quot;]/span[@class=&quot;button-label&quot;]</value>
      <webElementGuid>8b66afba-91c9-4c81-b634-43cc3b43bb2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cdk-drop-list-0']/tbody/tr/td[3]/div/button/span[2]/div/span</value>
      <webElementGuid>373aed96-34c6-4788-a115-d2a2859f6403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checklists'])[1]/following::span[3]</value>
      <webElementGuid>df63c93e-401e-42c6-b6a6-556c43911f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All fields are mandatory to save this record'])[1]/following::span[6]</value>
      <webElementGuid>57785b9e-7679-4410-8ce3-4cb6475fd6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Name'])[2]/preceding::span[8]</value>
      <webElementGuid>843c673c-cbb8-44e9-b90c-27986f60f781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checklists'])[2]/preceding::span[10]</value>
      <webElementGuid>a723d186-8cc2-40b3-ad91-433baa2ddba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Map Template']/parent::*</value>
      <webElementGuid>0034ee76-b014-48ac-a7f2-20fdc9108926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/span</value>
      <webElementGuid>12d23e14-d9c9-478e-bfaa-d60c015a7e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Map Template' or . = 'Map Template')]</value>
      <webElementGuid>bac4dffc-0393-4a47-b6c5-230ec729dbfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
