<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_COM-AUT-Dec312023</name>
   <tag></tag>
   <elementGuidId>f6b85f5b-9408-4b6d-9577-7cbe8a63044d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.text-ellipse.text-button.mdc-button.mat-mdc-button.mat-unthemed.mat-mdc-button-base.cdk-focused.cdk-mouse-focused > span.mdc-button__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-422']/span/div/div/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1ed20d38-0b80-48ca-a40a-29ee0d6e0020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-button__label</value>
      <webElementGuid>4c5c4cd2-6b08-4401-aa3e-5819013f5d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COM-AUT-Dec312023</value>
      <webElementGuid>e2aafdac-7412-410c-81f5-b21a9e3451fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-422&quot;)/span[@class=&quot;mat-content&quot;]/div[@class=&quot;ft-row border-0&quot;]/div[@class=&quot;ft-cell engagement-id&quot;]/button[@class=&quot;text-ellipse text-button mdc-button mat-mdc-button mat-unthemed mat-mdc-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]</value>
      <webElementGuid>9091bc83-4787-4fd3-bd60-fa51425185b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-422']/span/div/div/button/span[2]</value>
      <webElementGuid>9f3f5ea7-bd00-4fd7-95e9-5f25bce7ab67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AN'])[1]/following::span[3]</value>
      <webElementGuid>4974adc5-e012-4eb5-826f-849b91b05527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EL'])[2]/preceding::span[5]</value>
      <webElementGuid>fe9f0e0a-a944-4a60-a4fe-934863d9bd00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firm Team'])[2]/preceding::span[18]</value>
      <webElementGuid>a1ef2df4-a1b7-40b2-9199-775b61b3a45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COM-AUT-Dec312023']/parent::*</value>
      <webElementGuid>74629bc2-647a-4b66-93d2-cd2ee5651250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-expansion-panel[2]/mat-expansion-panel-header/span/div/div/button/span[2]</value>
      <webElementGuid>c0c8d8d6-a8c4-4c1b-b80f-027f358922b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'COM-AUT-Dec312023' or . = 'COM-AUT-Dec312023')]</value>
      <webElementGuid>3a3d2c3d-f9c8-4efb-9ef4-fc5e4765f4ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
