<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PravinTest 0701 (5 checklists)</name>
   <tag></tag>
   <elementGuidId>d862c899-adc7-4f83-acee-7f0db7f3014e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-expansion-panel-header-519 > span.mat-content > mat-panel-title.mat-expansion-panel-header-title > div.title-content > span.item-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-519']/span/mat-panel-title/div/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e9ec69d-828f-4088-9764-27bed102649a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-title</value>
      <webElementGuid>7aa7737b-0e4a-423b-accb-e1695613a3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PravinTest 0701 (5 checklists)</value>
      <webElementGuid>884fe150-ef1d-45ce-b28c-7ae810433d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-expansion-panel-header-519&quot;)/span[@class=&quot;mat-content&quot;]/mat-panel-title[@class=&quot;mat-expansion-panel-header-title&quot;]/div[@class=&quot;title-content&quot;]/span[@class=&quot;item-title&quot;]</value>
      <webElementGuid>d0f9bcb0-9db4-4009-8fcd-e4fc8d10df57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-expansion-panel-header[@id='mat-expansion-panel-header-519']/span/mat-panel-title/div/span[3]</value>
      <webElementGuid>923cba17-0145-4ff0-a420-eb4433bdd7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New_Cheklist (1 checklists)'])[1]/following::span[8]</value>
      <webElementGuid>ebcca11f-c6f0-4857-8a25-82dc297b83cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='one two four (1 checklists)'])[1]/following::span[151]</value>
      <webElementGuid>2ebf117a-029a-45bd-9d5e-ce5b26677fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PravinTest 0701 (5 checklists)']/parent::*</value>
      <webElementGuid>19f79bf1-a648-41c5-91cc-487caca1c771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-accordion[20]/mat-expansion-panel/mat-expansion-panel-header/span/mat-panel-title/div/span[3]</value>
      <webElementGuid>2ab78d77-27e7-46b9-8230-2b5e46479c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PravinTest 0701 (5 checklists)' or . = 'PravinTest 0701 (5 checklists)')]</value>
      <webElementGuid>d58fdd1a-6ba9-4f18-b779-98c00d8f2b1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
