<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PROD_LHS_inside_engagement</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3b310739-0c6f-42cb-868b-23d41d283d04</testSuiteGuid>
   <testCaseLink>
      <guid>35c41f09-26ec-4c8d-bce6-88d4f8a833e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Inside_Engagement_LHS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cc08e8a-f5a0-4cfb-ae23-951f889c3df4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b1b945e-73b1-4139-ae88-806be2b6cec4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a67bbc0-aff9-421d-80a6-7b3ee7f686d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7211ed3b-171d-4f1f-bffa-3eb5a8f60033</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Inside_Engagement_LHS - Docs_Kebab</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26aabb59-6fa5-49a9-b5d3-ef1d5ef37496</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aeab06c-3155-4a4a-ad06-e3c0f9d870b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7db316f-984e-4a57-b228-1780ecfd3fe8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a01f83ff-ce55-46f7-9120-100762b35e2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Inside_Engagement_LHS_Procedures_Assets</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d53bdff8-c7d7-4110-a321-54581d765e73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb7e684c-c861-4b91-b8ef-30b2460006ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0947f74f-4efa-417e-a81c-a5dd0d4b0bd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4c4f1d9-a174-4eb7-a177-cf8c0e6853af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e03badc5-fc94-48a4-b7ce-19fd10f04526</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Inside_Engagement_LHS_Procedures_Liabilities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fe1462c-fc44-499d-809a-9fa7ff2448d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1842a1e-2652-4399-8a15-7568fcb65a7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5464c71-3754-4204-a870-342ae865e69f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>772b75de-96ba-455a-af66-d16c4b900867</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bc47888-5c4e-445c-a5a6-dfac815ee6f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Inside_Engagement_LHS_Procedures_Equity</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32d46c62-1599-4c59-99f6-9cbca4df9c1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70f00897-9763-47f8-ba2d-bae1251d5704</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6dec47f-1f58-456f-9519-619d5847e554</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29b856f6-882d-4a18-965d-8b11c3f4fe96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b8629b9-3be3-4cf3-9f47-b9d775616347</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Inside_Engagement_LHS_Procedures_Revenue</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de543c4b-f915-4136-8c3b-8b443a44c5c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c34b95f-76a3-4b3c-9434-b0ff86197bae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4067d25-19f7-4797-ad4c-c6494803681e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38fb8447-5c0a-483d-9920-204885f8409d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46b197f6-74e3-447b-93bb-9c20dbf95fe6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Inside_Engagement_LHS_Procedures_Expenses</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08e75b35-895f-4ee1-8ad2-6691de108ad3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2da1de16-69c5-40b7-a0d5-97d7b2678625</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a74f23c9-7a41-4b51-a780-bd5e1e010f09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d043e722-deb4-4116-932f-60e46e91d7b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
