<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PROD_REQ_ISS_COM_PRO_SIGN</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f6c2acdb-c7a0-4413-8e37-30ef3d29b6bf</testSuiteGuid>
   <testCaseLink>
      <guid>b1c99de9-fbef-4981-ba8a-4496902d7ab9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Script6_Inside_Eng_RHS_Requests</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6f8dc40-6335-497f-86a2-afe78b7a517f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a540d67-1175-4b18-a8e8-9dbd2fdea922</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35cc924e-ea12-4eec-8a63-48ab5fd6f598</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da6ee61a-82bc-414c-8a18-1bbb71079396</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8fc67d1-bf28-4945-8d0d-7052ae064777</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Script6.1_Inside_Eng_RHS_Issues</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>259067bc-4372-4ad8-8335-fdf1fff89341</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa426487-e9e8-42a2-8fda-4498e0f2fc5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>365d3308-927e-4d45-8bb7-7cb003a3d102</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed93053c-1887-444c-9194-87a04419ed63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2401b53b-d82d-4d2d-9176-6b341e5180a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a833fc8a-bae3-41ef-9bc9-64ccbcb8a61f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Script6.3_Inside_Eng_RHS_Comments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94bf5c8e-abdb-45f5-bb4e-fb2bd0682e6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7ff0538-6e18-423b-96ef-7f5877f7876e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9276dc03-9369-4b0d-b4f5-748cee9bbded</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da2a52a5-87ea-44a8-b219-a6f85182e875</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34ae66e2-573e-44c7-947a-8f49de706e70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af367c3f-21cd-495e-a1e4-500d0a202257</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Script_31_Procedures_Com_Engagement_PROD_All</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31d7b412-261a-411b-8b6c-e4d70fab5682</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9585e16-191b-4b78-a342-262b5e16324d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f41599-ea40-46f2-8e71-8659c469b22f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46d4bca4-74f0-4b21-ac0e-347fb3c1563a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2645930-ee0f-409d-94a9-3abd904443b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/SignOff_Page - Comp_Tax</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>215a9216-9622-4db4-bf3b-09697136b772</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>188d9eec-c873-44b1-8039-c09b17925288</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bd4596b-c36b-4412-9b93-95ea4456c755</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
