<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PROD_LHS_inside_engagement</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3b310739-0c6f-42cb-868b-23d41d283d04</testSuiteGuid>
   <testCaseLink>
      <guid>1a0446e3-0fb1-4313-99d4-ad2a0d561970</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Inside_Engagement_LHS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cec5d9c4-14be-45f1-a05d-aa2521701167</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92197828-3e46-4f03-ada7-27d9bc61c9cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b6c2914-bdad-42c2-9a0c-2f6e0aa5d179</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b2493a8-b1f5-4bb5-a830-989862689ed1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Inside_Engagement_LHS - Docs_Kebab</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2487f93-6167-4263-8c93-7fb833eacaa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9e9b124-bd5c-4362-b3dd-78d01b65efd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3067393a-f682-486b-8828-eea303d48b5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c95930aa-e6b6-4076-aadf-b331bccc0afd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Inside_Engagement_LHS_Procedures_Assets</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b82423d-bcf7-46f8-a980-5989e8523652</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cca29b61-2173-4356-9825-f63ef3cb3208</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb0d9369-b455-413e-ae91-f147030af438</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d718fa2-b5e1-4822-a752-ce6dd65cbcc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7eea2ea-f23f-4e29-9483-c3803fd353d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Inside_Engagement_LHS_Procedures_Equity</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec5988fd-f783-4480-9c5c-13bb997ab7e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ae3f6c2-79cb-47cb-9510-1639169e3199</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8c7475e-7699-4481-8325-ea721d3b0e3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13d82f45-9d36-4e0b-8005-907510af67a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e52e5022-7b7c-4796-a0b0-1504060180b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Inside_Engagement_LHS_Procedures_Expenses</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d930bb6-7790-4c24-8205-fd55fe371105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c100b1ad-e477-4c70-a4a1-b33df8296fb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca6ace41-fb7f-4260-abfa-d58c509b5677</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03cd5dd8-f4bf-4087-86c9-f3e3fc487f2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b63055a-54e1-4b2c-9b05-9e83eaf1942e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Inside_Engagement_LHS_Procedures_Liabilities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d83405a9-45e1-4ecc-806a-47e3cfb2f779</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>512e5ca4-6853-42f6-bc0b-5b7ab5e8a547</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bea9c2a8-84fb-44b8-bbcd-ed1b99b9ee23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a457c4e-acce-4670-a8fa-fe517794b0c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>596d7e42-f7f5-4420-9fc7-f6d2cbeeca3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Inside_Engagement_LHS_Procedures_Revenue</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d60f5c8b-5789-4052-8e16-35b418431e97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5ccfb84-b209-43a1-9e94-e19423a382ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2b7ea59-5810-41d2-95c9-bac1cf685064</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27e1fe42-1a00-4854-9700-eade1c47a412</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
