<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SingleTC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a34a3b38-68d8-4272-8b90-db4c9db6d483</testSuiteGuid>
   <testCaseLink>
      <guid>3e5dac92-db88-4526-8857-c63b43c2d77f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Checklists/Canada_Tax_Checklists/1.Copy_TaxChecklists_From_Master_To_Firm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>560cc4ca-81dc-4d3f-9dc9-bbdd4db0ba96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da204c0d-cc30-4684-87d9-9a5c8a50c522</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10af0ba8-0a55-49f9-bc7a-0dbb15bc50f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0afe6ba9-7ca3-443a-b539-1d24a430a428</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Checklists/Canada_Tax_Checklists/2.Add_Question_And_Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fd99e1c-b060-4bb4-97e7-50c7b2fa08d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16296772-5d70-4e6b-9709-ac42f86d96ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0096841d-3463-434e-9a87-ee7dd11607e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91d0524e-6d68-4b00-a816-639325e5cd96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Checklists/Canada_Tax_Checklists/3.Checklist_Kebab_Options</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01de054c-170d-4385-a373-ceb315e814ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c883e81e-7f61-4324-81f0-a63c406a9808</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b173287-5597-4b2d-a069-288616ff2188</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d6bff94-83c3-4656-a724-2dbbd19b6f62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Checklists/Canada_Tax_Checklists/4.Map_Checklist_Engagement_Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1ecd6ad-129f-4b08-8518-9fe910dee22e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3ca580c-ad86-40e2-a735-2f94ffe74d74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1b59641-5ebb-4d16-b59d-05f4599f5110</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9705060c-be90-47d9-97dd-98bb707ecfbe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Checklists/Canada_Tax_Checklists/5.Create_Engagement_Tax_CANADA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d58f680f-c77c-4d66-8c87-8c8a5ba69209</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f485af50-f8a0-4703-9f3b-b2eec5e92f1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cf02179-f2bb-4c4e-a410-b1299035ac85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d07056f0-24bd-4d50-b7ca-79256835e51f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1014f0c9-abf0-43ec-a09e-f1e30540f70a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_Prod/Checklists/Canada_Tax_Checklists/6.Checklist_Inside_Engagement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76aef4cb-0143-4578-8ece-38b1a1caa5be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f99e194-bbe0-4f55-a33e-48ceb1efcd97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6865ef10-ba18-4551-8f82-f8f955696256</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
