<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UAT_Admin_User_Access</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>83d8e6e5-3316-4e32-a079-6e5b2afc3f48</testSuiteGuid>
   <testCaseLink>
      <guid>f3e58c79-10c8-4267-bee5-29d8a701ee7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_Admin_User/1.User_Access_Default_permissions_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f00af813-3b6c-411e-b41d-ed90e88c90fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ca5ed80-b21d-4bea-bbf9-4af3f0d89a90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9edb2539-7f7b-4899-94b4-944b739e933a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>683497ab-c5f3-4090-aaee-352958b9e733</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a517eb-000e-4ef9-a059-d4aa4e3788d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccc4c8ef-94c6-437c-8584-9b8dfb20d4cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_Admin_User/2.User_Access_General_Settings_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54f6ce00-79c3-46ae-9699-0053567114a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afbca4c4-e74e-4784-a41f-e87b6f334e68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57a03c6b-6288-41f0-b35b-b50373fe91e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccb61442-a54b-43ea-9524-ad407273eb19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39a337c3-a013-4f81-b294-d31f88c590d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f369bd0f-b6e9-448c-a15f-e79af8103f20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_Admin_User/3.User_Access_Team_member_settings_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa4e4b16-1d2d-4850-9a5b-a1683b75347b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e451268-fb93-4662-befa-373c89a30431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8a4c528-d64d-40a2-8c81-a3971baeb839</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6dfb4f9-3529-402d-93d0-9ede8f827137</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50b75eb7-af45-4164-b30f-4a82af55cd6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>381ccc51-29ab-4738-9fb3-a55ba3c97548</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_Admin_User/4.User_Access_Client_Settings_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a2deed6-8e74-4df1-ab6b-7cb06f7c3604</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cd37192-a75b-46c7-a14d-8e6ad194ab37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>423a3252-2869-4bf2-a69a-43df6dbbceda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a40b7751-fd9e-4f6f-97ce-bc94dd8986f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>310f3287-1c04-495e-ad44-dba2b4972cfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f65dc9ca-b713-4007-8a98-bcf941b37d56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a74126b-40ab-4b5f-8e2d-53c5da9c74d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21c44445-693f-401a-8d8e-74b03fff8def</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_Admin_User/5.User_Access_Engagements_Settings_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43d595cf-9883-4ad6-9d68-998565a81bec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c9a2ebb-53cd-4b11-87c1-c2f3887c0a80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67abe59b-9bbe-4001-ab2b-a3b212017fcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f421022-7aa8-4132-8fe9-0a21461727d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9be43047-03ff-44ae-9d11-fcb101d642ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d79eccc4-c5ee-49ad-befd-4c8188cdb23c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a7f726a-a507-455c-a5c0-8874d6dd0215</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e43a724d-b4cf-46d4-87cc-b90319e42c9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5878678-d80a-48f1-87af-10739653b92a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_Admin_User/6.User_Access_Template_settings_Admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce73b03c-4581-4b91-9cb6-338af2da8d76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4e93391-ab18-46e0-a0da-9a9ff4bf5c47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>def58b34-6624-4dc6-965e-46de967779ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e5bd7b4-33ea-49f1-881f-553a89d32c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11946a3e-9432-40a0-9830-99da7022695f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bc39108-61c0-4561-bb1a-bbad0ca4e255</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4aa9ea41-236e-45ff-98c6-a098c830394b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b06e1691-26bc-4683-8d9b-0ac91b54b3a9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
