<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UAT_User_Access_SuperAdmin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>01dc2224-403d-472c-ab90-5d6e3c82e99a</testSuiteGuid>
   <testCaseLink>
      <guid>bed28210-2a13-4423-a5dc-9e240658b9b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_SuperAdmin_User/1.User_Access_Default_permissions_SupAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e49951dd-c290-4c54-b471-f15869457734</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97f556f6-0a6a-4360-b771-bfffa136a736</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2602219c-5240-42ac-8af3-db3d4c6c0c12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>187c9f02-35cc-4092-8e1b-a3faa4f376cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68ea19ed-b100-426a-911c-0a3bfc2cb3ba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3600ae08-fa48-4efa-914a-2d7c346aab76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_SuperAdmin_User/2.User_Access_General_Settings_SupAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c241e08b-3709-4120-acf9-a0c5ef734944</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d390ee7b-c7ea-4ae0-b25e-17401f317ac2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f5ec9f9-7a9d-410f-a91c-80b87a49f524</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21277a5b-14de-45a5-bce0-7cc7576d17e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>542af0a2-a1a5-42ec-9b47-f852a46f4f6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d1b66f0-1145-4897-80fa-000c333d25cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_SuperAdmin_User/3.1.User_Access_Team_member_settings_SupAdmin_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e5c9e09-463b-4313-9b7a-0ca1a1a6020c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dce36cdc-2f3c-4c5d-aed5-8e926c63450d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62ceaa8e-36c6-4f14-aa16-36aa08bb64df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcbd34e3-008f-4627-adaa-100c85178812</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e7a2b5e-0440-4cec-a7f8-5af346691b27</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2dc58b6-c7ba-4e8d-9e00-a3fbccb4e32d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_SuperAdmin_User/3.User_Access_Team_member_settings_SupAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17be758a-62fb-45a6-95a8-f198e3e08cc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba330715-6b32-4d7f-acdf-c3b8914072ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa4555d0-1aae-44fb-a124-280cb942e1b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>911529b3-6aa3-4e9b-826f-ab607c416903</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0759c17a-839c-4b38-93e1-cd3d93d45a11</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32a6a21b-10c5-49cf-9223-26e48349e316</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_SuperAdmin_User/4.User_Access_Client_Settings_SupAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f6adae4-8363-42bc-a9d0-6cffbb8c09d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9f1fdd0-7c92-454b-8117-974b3826f7fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc8bdabb-0d27-4935-979d-f01fb85b1145</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9e78db8-e8e8-403e-b1b6-75506bd3e9dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d85f9b8a-0397-48ea-8496-c9c743ecd0e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdb9dfc1-afb2-4811-bb6f-4daf58e73e5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53b79385-03d4-4d55-9ebb-6de0e8376af4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>437bc1a0-7e85-411e-ac2c-1cb4b6eededd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_SuperAdmin_User/5.User_Access_Engagements_Settings_SupAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6ca90d1-6df9-4af6-a32a-9ded8dfb33a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d23712de-940e-44f0-a043-f1d525a14aae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ba8b7da-eef9-41ac-ada6-ff4bbeeca064</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b619794-a9cf-4941-a1fb-215ac26a2c36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63135ef9-3d79-4310-b218-fda31c6d89e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82b4d1f7-4b91-4009-a35c-3a4d2cb2abff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78b0ec1c-7355-4dc0-a04b-f30f3c69cf3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fbad174-7b1f-4cff-877b-3e710b4264d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8509db6-41a8-4f44-bce9-5961c32e15fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/User_Access_SuperAdmin_User/6.User_Access_Template_settings_SupAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff9000e7-bb59-4a4c-99ed-73f43a01fe47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db3f4f23-e894-4e86-b909-5e7a9e19f471</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed06db5a-9ea3-422e-91e4-8f41606d5349</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f95e012d-02d0-4b62-ad62-31a94d83e748</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b9b936b-0173-463a-bd1f-cf06f7ff518e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc59bd17-fdba-49b8-84f4-afa68a7b3bf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7a6a91c-5d87-4d4e-9c2e-6389e6d00c9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>450dba30-0fa7-41d5-807f-4f5383ccccee</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
