<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>USA_Signup_Onboarding</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>22710587-ab3c-432c-9498-ea1cfe074b4e</testSuiteGuid>
   <testCaseLink>
      <guid>9c9e52e0-4c38-470e-a8fa-bcae1fcf5792</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script_23_SignUp-Countable_USA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74f07266-b39c-45c1-89d5-79b14cd2c3ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>440efe2a-32d6-47a9-af4d-49e619e694bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e64a48a2-fed1-4841-bfcb-21a36e176d93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a4eda6f-299e-40cb-a842-6bff1e16fa76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Countable_UAT_Environment_Scripts/Script_24_OnboardFirmTeamClient_USA -ManuallyAddress</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d7cfaa1-a5ab-4362-ba82-0178abd15f1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e770771-01bc-4939-a27e-256de3f7dcdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49cf9564-8e39-43c4-bc5b-bfac4cb691c4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
