<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inviteEmail</name>
   <tag></tag>
   <elementGuidId>d6457184-c1cb-4de0-8d54-eb94f66ab93f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody/tr[3]/td[14]/div[1]/button[1]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>69109f81-1fe4-44c8-8f7a-a17d573b34de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1716142939538</value>
      <webElementGuid>d44e3dfa-1dbc-450c-81b1-073d5cad1bbf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
