<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SentInvite_MyClient_1st</name>
   <tag></tag>
   <elementGuidId>1c4b2e4e-e1ea-47b5-855b-ec0e19bdd6ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@src='/assets/images/ui-uplift-icons/global/email-box-icon.svg'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
