<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_Access_Permissions</name>
   <tag></tag>
   <elementGuidId>ba6d7df6-8dd7-4892-90aa-b2ced1387d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//mat-accordion/mat-expansion-panel/div/div/div/mat-list/mat-list-item/span/span/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
