<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>View_Client_Access</name>
   <tag></tag>
   <elementGuidId>5f77a6e0-b43c-4a57-be97-31971c8d22e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[6]/mat-checkbox</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
