<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose Category_Object1st</name>
   <tag></tag>
   <elementGuidId>ed4c6296-d4d0-4618-bb38-99949a74b375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-1']|//mat-select[@formcontrolname='category']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44f52922-681a-4a14-a07e-975f12fe5f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-select-value ng-tns-c2400438669-28</value>
      <webElementGuid>ca0608c0-4981-46a7-a66b-01abb7af18b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-1</value>
      <webElementGuid>5e7f8b0d-da58-4cef-a9f6-2b9272d6995c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Category</value>
      <webElementGuid>973e4ee4-22c8-40a9-bdd3-eda05bf21bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-1&quot;)</value>
      <webElementGuid>e5acae78-e711-4ce7-891f-3e7428935516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-1']</value>
      <webElementGuid>30cc9d77-93b3-4011-bb9b-d9e053b3930a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-0']/div/div</value>
      <webElementGuid>68a521be-6673-4982-b7e2-726d8e346c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Category'])[1]/following::div[2]</value>
      <webElementGuid>e289e4d8-f511-48b0-ad27-eca1942c5f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Details'])[1]/following::div[8]</value>
      <webElementGuid>d61f7388-1378-4f47-846b-52201785e7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member ID'])[1]/preceding::div[8]</value>
      <webElementGuid>a02af705-3649-400e-b59e-3a2a80b17431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div</value>
      <webElementGuid>1f023edf-91b6-4293-8d38-43a4812c1365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-1' and (text() = 'Choose Category' or . = 'Choose Category')]</value>
      <webElementGuid>2729bd08-efcd-4b8d-adad-a8cbeab67473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
