<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>QA Onboarding_Sign_up Suit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>89c9fe5a-7b70-4f9f-aded-88dbc478f781</testSuiteGuid>
   <testCaseLink>
      <guid>50217e15-8bfc-4c55-a935-bd398347e2ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/QA Server/SignUp-Countable_Canada</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7bc1b8b4-81f3-475c-8313-4c5a3b582066</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data/Signup Data-Canada</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7bc1b8b4-81f3-475c-8313-4c5a3b582066</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailSignup</value>
         <variableId>fefa9c67-ea7a-4d6b-9f9d-f3ac5b86f174</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7bc1b8b4-81f3-475c-8313-4c5a3b582066</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>yopmail</value>
         <variableId>995c5d61-b966-430c-b09d-23f9c30ec3b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8d83482-fa64-4507-bdb8-949152c01e8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/QA Server/Onboarding Updated_Canada_New</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6316f0a4-a805-477e-8558-e7ef20160e71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ea8d080-b688-4f14-8227-3d49de86c641</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d078800a-3232-4189-8a32-dc81f35ea34b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>876f0d7c-e926-4d7f-beb2-d9b4d24ec4d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15dcf430-b3fb-4114-b4cd-5044ce901883</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
