<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verify</name>
   <tag></tag>
   <elementGuidId>59a88558-62e9-4a15-865d-eaae26f16f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Verify')]|//button[normalize-space()='Set Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14f8f5e4-a603-464b-b5d4-7771381f22b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat.adinovis.com/setpassword?token=N2M2OTNiOTItMGQ4NS00N2IxLTljNmUtNWJmNWJhMWRjMTQ2</value>
      <webElementGuid>f8f1495f-5e41-4e76-bd21-bfd20bd089f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify
                                    Email</value>
      <webElementGuid>2d71d76b-9d89-4d49-9fdd-e8f830ed6c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/table[1]/tbody[1]/tr[4]/td[1]/a[1]</value>
      <webElementGuid>d17357ec-d652-449f-aeb8-48ec1527cd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Inbox/iframe_Undo_ifmail</value>
      <webElementGuid>9ab72c77-55a1-4701-a1d1-f85c27bb8b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verify')]</value>
      <webElementGuid>0d7718d3-5c3e-49d8-bc1e-139ba0e4db8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verify
                                    Email')]</value>
      <webElementGuid>4917fa91-2627-4d60-adc5-a10c2373bb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat.adinovis.com/setpassword?token=N2M2OTNiOTItMGQ4NS00N2IxLTljNmUtNWJmNWJhMWRjMTQ2')]</value>
      <webElementGuid>596d2191-1a82-4721-9164-60fc60197b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>12e0e490-2a9d-4962-badb-e64cc2855c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat.adinovis.com/setpassword?token=N2M2OTNiOTItMGQ4NS00N2IxLTljNmUtNWJmNWJhMWRjMTQ2' and (text() = 'Verify
                                    Email' or . = 'Verify
                                    Email')]</value>
      <webElementGuid>0e75d1dd-c80d-46e0-ae2e-125caaa03242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
