<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Button_Team_Staff_Sec</name>
   <tag></tag>
   <elementGuidId>33c1f0f6-3cbd-42d8-a93a-127e684f5db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@title='Edit'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/app-root[1]/app-dashboard[1]/div[1]/div[1]/div[2]/app-teammember[1]/div[1]/div[2]/div[2]/mat-tab-group[1]/div[1]/mat-tab-body[3]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[14]/div[1]/button[2]/span[2]/img[1]</value>
      <webElementGuid>118ab1ac-528f-4f69-834a-d85c69e847b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//img[@src='/assets/images/ui-uplift-icons/global/edit-pencile-Icon.svg'])[1]</value>
      <webElementGuid>07726c62-b2e1-4870-abed-1ed5703540d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
