<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Button_Team_Staff_Sec</name>
   <tag></tag>
   <elementGuidId>33c1f0f6-3cbd-42d8-a93a-127e684f5db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/app-root[1]/app-dashboard[1]/div[1]/div[1]/div[2]/app-teammember[1]/div[1]/div[2]/div[2]/mat-tab-group[1]/div[1]/mat-tab-body[3]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[14]/div[1]/button[2]/span[2]/img[1]|(//button[@title='Edit'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/app-root[1]/app-dashboard[1]/div[1]/div[1]/div[2]/app-teammember[1]/div[1]/div[2]/div[2]/mat-tab-group[1]/div[1]/mat-tab-body[3]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[14]/div[1]/button[2]/span[2]/img[1]</value>
      <webElementGuid>2106c04e-71dd-4a68-adc8-ee111381b94f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//img[@src='/assets/images/ui-uplift-icons/global/edit-pencile-Icon.svg'])[1]</value>
      <webElementGuid>d09b800b-30d0-48d2-984a-81a43a58f93c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
