<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyPartnerCount</name>
   <tag></tag>
   <elementGuidId>36d4951c-044f-4a52-947f-e7cbb97d5b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[normalize-space()='5']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h2[normalize-space()='5']</value>
      <webElementGuid>e67aff36-f13b-4b9c-b23f-92f4efdde2ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
