<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Client_Onboarding_Items_Count</name>
   <tag></tag>
   <elementGuidId>2f48f6ce-7e9e-4eb2-8ff3-d5e28cb27c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel[contains(@class,\'client-onboarding-panel\')]/div/div/mat-expansion-panel|//mat-expansion-panel[contains(@class,\'client-onboarding-panel\')]/div/div/div/mat-expansion-panel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
