<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Procedures_LS_Count</name>
   <tag></tag>
   <elementGuidId>4d277d12-e911-47fa-8760-31483f2ce02e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel[contains(@class,\'procedures-main\')]/div/div/mat-expansion-panel/div/div/mat-expansion-panel/div/div/mat-expansion-panel|//mat-expansion-panel[contains(@class,\'procedures-main\')]/div/div/div/mat-expansion-panel/div/div/div/mat-expansion-panel/div/div/div/mat-expansion-panel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
