<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RegressionSuiteUSA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ae68914a-1d66-4621-9d15-329d4320cc04</testSuiteGuid>
   <testCaseLink>
      <guid>56a6e400-e871-4984-8f45-9df57644b5c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/SignUp-Countable_USA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e61e8592-36f1-4045-b85e-ccf824b83036</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ba041a9-3750-47d9-a969-4cdb5e9b5327</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9c677e1-7873-45e6-b1d5-147cf96f149c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/OnboardFirmTeamClient_USA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46c3005c-adae-4373-8030-7447df02836b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d311be06-514e-499e-a6f0-74c2725ffd4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d5664b-33cd-4e5f-bb9f-a987c1bc3ae8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5af3cf6c-3214-4fba-acbf-946fbe273213</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/AddTeam_All_Reg_Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bcad048-f6e8-4c58-b470-5ceb57ea0a5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4955381c-10ef-487a-aba8-5cf3a0b37b77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>873013ba-e741-410c-a16e-5f53adf296ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4366d2c4-8bbb-4557-b753-2a8d6d61f873</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8731e0d1-6afb-43c7-ac0c-55020ca66157</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/AddClient_All_Reg_Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1124ca7e-1aa0-4c97-b748-7d9df4852e4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfd6410c-82aa-4a51-8387-3d2b83e97079</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
