<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression_Suite_Canada</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>eee79c6e-dc09-42b5-982e-6b99a672b5f7</testSuiteGuid>
   <testCaseLink>
      <guid>6eb012af-41fe-441c-b9dd-08cca86978f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/SignUp-Countable_Canada</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78212f58-da78-4809-82ae-86615f06bbdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9b07514-ea31-4f71-86fa-659821a9d3df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc0ba1cf-eb16-407e-b308-08c1cf5ed8cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/OnboardFirmTeamClient_CANADA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0c5db49-028e-4442-bc20-363621a092a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0844e58-6f94-490d-9ccc-42780f7d191c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>714c999b-f102-40fd-bbb6-85cb4bfaab84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aac1896-143f-4458-86c8-4ed015f8408c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b8111b5-15a3-46d3-9a89-12ecfef8d391</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9ecc769-c6ca-44c8-93e9-e0bdd0c50b30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/AddTeam_All_Reg_Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bcad048-f6e8-4c58-b470-5ceb57ea0a5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4955381c-10ef-487a-aba8-5cf3a0b37b77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>873013ba-e741-410c-a16e-5f53adf296ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4366d2c4-8bbb-4557-b753-2a8d6d61f873</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4009f7b0-6307-4bfe-9be5-86ea9ed3dd9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/StripePayment_Essential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fac0bce0-d722-46c6-8df8-1f676c89b40b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a40ac5b2-520d-4380-9a5a-d4788e9d0b13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/AddClient_All_Reg_Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1124ca7e-1aa0-4c97-b748-7d9df4852e4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfd6410c-82aa-4a51-8387-3d2b83e97079</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
