<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sign-Up Onboarding-USA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f9643fe2-0a7b-44eb-a4f1-ee62be423728</testSuiteGuid>
   <testCaseLink>
      <guid>a28a5c70-0821-42c7-aec4-e56c30e8bf05</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/SignUp-Countable_USA</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dd4bd94d-388d-469e-8436-c501dcdf0787</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data/SignUp Data-USA</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dd4bd94d-388d-469e-8436-c501dcdf0787</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailSignup</value>
         <variableId>e61e8592-36f1-4045-b85e-ccf824b83036</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd4bd94d-388d-469e-8436-c501dcdf0787</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>yopmail</value>
         <variableId>8ba041a9-3750-47d9-a969-4cdb5e9b5327</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ecfa7660-681d-400b-be4d-d019c4cc2091</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RegressionTestCase-UAT-Env/OnboardFirmTeamClient_USA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46c3005c-adae-4373-8030-7447df02836b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d311be06-514e-499e-a6f0-74c2725ffd4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d5664b-33cd-4e5f-bb9f-a987c1bc3ae8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
