<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UplodClient_Data_Onboarding_Import</name>
   <tag></tag>
   <elementGuidId>0670cbc2-cda5-4f82-b934-c95d0fa56f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='photo'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//div[@class='file-wrapper'])[2]</value>
      <webElementGuid>5b2db86a-f51c-42e7-9ec0-b76b0eb77145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//input[@type='file'])[2]</value>
      <webElementGuid>b6764e6f-94f7-4656-9060-1722814cd2fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
