<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TB_ADJ</name>
   <tag></tag>
   <elementGuidId>ebd88395-b6a3-40c6-a64c-53ba0cdbc22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[normalize-space()='TB']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
