<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1st_Request_Kebab_AllRequestTab</name>
   <tag></tag>
   <elementGuidId>85af20ac-7645-4788-9988-95716edce049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//mat-expansion-panel-header[@role='button'])[50]/span/mat-panel-title/div/button|(//button[contains(@class,'kebab-menu-button')])[last()]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
