<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Client_Onbrding_Folder_RHS</name>
   <tag></tag>
   <elementGuidId>0c9a6261-02e1-4aba-a721-8e12db1f56cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='listbox']//div[1]//span[1]|//div[@role='listbox']//div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div/div[1]</value>
      <webElementGuid>14b908a1-baaf-482e-a7b9-a4e2ce7fd05a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
