<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_EngagementID</name>
   <tag></tag>
   <elementGuidId>d7bf60e6-b2f1-4504-bae3-0990e90f24c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form/mat-form-field/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//img[@src='/assets/images/ui-uplift-icons/global/edit-pencile-Icon.svg'])[1]</value>
      <webElementGuid>cd8b562c-1d4e-42e8-9df1-a39dbadf3329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@title='Edit']//img[@alt='icon']</value>
      <webElementGuid>dceec371-8846-4ca6-b251-283addc766d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//form/mat-form-field/div/div/div/button</value>
      <webElementGuid>272805d2-1362-4133-b50a-a4488f476ba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
