<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Comp_Checklist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3a618d11-baf1-405b-bc88-66120023c932</testSuiteGuid>
   <testCaseLink>
      <guid>d792a80f-98ec-4997-97e4-7f5e37260bad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Compilation_Checklists/1.Copy_CompChecklists_From_Master_To_Firm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cfec062-dfed-4891-9da4-e43caee1bd47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ced1a6-beb6-46f7-957a-af19815f73ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfb4e246-4bb5-42ea-8034-56d68df7c609</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1556da5-98a8-43a5-b84b-56979238d9f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Compilation_Checklists/2.Add_Question_And_Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f298a983-d5d4-4e93-b721-a7e161052009</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>596e97f1-6a46-441f-9658-5872b82e7535</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f183073e-97be-4c6f-85a9-80eb64ec2063</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6f4dd54-bf42-4687-a243-2f9b75304391</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Compilation_Checklists/3.Checklist_Kebab_Options</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa2979dc-2c0c-4604-8efa-8f8818a5e1ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>609a6c36-1ba6-4034-8393-cfbf718dfd47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7286529d-ed9a-4f1a-9230-4459b2540716</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00c193c5-b8f3-417e-bc55-90856f00b9e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Compilation_Checklists/4.Map_Checklist_Engagement_Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a86c2941-24a5-4445-9d5c-985079e6e321</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f81d1c74-d92e-4e1c-91ac-0ff44e720d5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35dde23c-523a-4046-8967-aeac9d62521f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93de7c0b-f038-45f1-942b-9bca361e5eba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Compilation_Checklists/5.Create_Engagement_Compilation_default_template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44bc419f-2898-4b8b-bcd6-665398342012</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16ad04bd-f615-426d-9d5c-c0946983dac0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0884704b-4739-49f6-a9ff-9418a7155c12</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf2e405d-cda1-4105-9d34-4c5204ef952a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Compilation_Checklists/6.Checklist_Inside_Engagement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7082080-6d7a-44a8-9e5f-73b2cf11a95f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>601555f8-70b8-4d2f-bea0-741d95204869</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1b1e861-32e3-418c-b2f1-18c48d03fb39</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
