<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Review_Checklist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3b26ab33-91a2-4f6b-abd2-374563a485d3</testSuiteGuid>
   <testCaseLink>
      <guid>fe45dcc7-c7c7-4a8f-93b1-e9d51994341e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Review_Checklists/1.Copy_ReviewChecklists_From_Master_To_Firm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbc264d0-5c9a-43ca-bd33-87810eff2ee5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73b625d7-d3e6-464b-86b5-d745d96f178c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aea8570-6369-44f9-9bfe-a4c811ebffc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b6db0d5-5b2a-42f7-a099-7761961c4060</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Review_Checklists/2.Add_Question_And_Category_Review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de9b2c30-91cb-440e-9da1-ec7622c5b05a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13acaedb-7908-48bd-953f-59f05e7ca64e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46ce7deb-36c8-4002-9ec5-770b7c6e265c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60714044-0953-49a3-be1b-50153804186a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Review_Checklists/3.Checklist_Kebab_Options_Review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>145f2de7-ef1c-4382-9bbe-d568d40450e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca2665c1-5b9b-4d8d-adb9-11fdacbc4613</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2792223b-97c3-47ce-ad6e-3297901a531b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>696462c5-99ae-44dc-8fe4-706d814ec3cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Review_Checklists/4.Map_Checklist_Engagement_Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca3c6138-ea14-44fa-b823-b2e4b8425627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a1a89bf-ebda-4947-b883-148373f6e162</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c6308a-950a-4baa-9579-cd492f0a586b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba0c80a6-bccd-4b64-9de6-6e449b78bddb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Review_Checklists/5.Create_Engagement_Review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4b3a149-8ac8-4f0e-9a1d-8fdf9b83b21b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8de73fb9-7de6-47fe-a30e-d21172280992</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5de1385-fb31-4908-86a6-49426ca16b47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0a85cb9-1d03-4965-bede-050454041ec9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Review_Checklists/6.Checklist_Inside_Engagement_Review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34de61f9-6c9f-459c-be27-9fc5de38b140</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>764eecf4-c65f-45a4-a829-9568a968e597</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06ae4ecd-b2bb-41e8-904e-8772ba4a6a05</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
