<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>T2_Checklist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2d0e868b-88b4-487f-9e82-66a6d3e749e1</testSuiteGuid>
   <testCaseLink>
      <guid>6323b368-c470-4bca-9300-efe3c4ebd99b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Canada_Tax_Checklists/1.Copy_TaxChecklists_From_Master_To_Firm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e92246e2-1cd3-4c9a-bdf5-18dead008e4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4d8f429-95fe-4e1a-911d-265819c7ca13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>802fa495-66f7-4067-9f6e-f6de0ba0b772</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b279f77c-7184-4603-a168-02a8b9ff29a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Canada_Tax_Checklists/2.Add_Question_And_Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8316f395-a780-4bb6-8d2f-c457895dc54d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7d4b8a0-0816-4961-8f6d-e4b0f5e8f000</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3db00668-2748-4fa4-8ecf-df3cdfc7667f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29001abe-17b9-431a-ae70-4412976f1294</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Canada_Tax_Checklists/3.Checklist_Kebab_Options</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf87ff52-1ab2-4883-b008-fe193c12ed95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7319292f-90a1-4de4-b8ba-28a8b14fc7de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c764052f-ae7a-4c91-be41-0f4d4f389cd0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a99b2400-884b-47c6-8d9d-87366583b99c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Canada_Tax_Checklists/4.Map_Checklist_Engagement_Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49d98d4b-2757-4176-8858-c2c2aae0e40a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8b98db4-ed30-4382-a673-35524c8cfe05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4673dc3c-4c16-4f10-b205-a7ca8f15aa53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10475eb1-8db2-44b4-ac1b-d7d4c49c04de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Canada_Tax_Checklists/5.Create_Engagement_Tax_CANADA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>891a6bb6-d549-417a-9a8e-f452c5891542</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a96c29cd-57f2-4b67-a510-74f1a0f7d199</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed61156c-a447-458a-a752-f3763a20488a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cc26593-b43b-489a-9223-0ecf0ca2303e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/Canada_Tax_Checklists/6.Checklist_Inside_Engagement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cbcd7f4-9e17-41b5-94da-7ed4febe7a78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b404be8a-e4e9-4770-b7df-fd7facbe7d86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c03117ba-6e05-4315-9ec0-bad151010aaa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
