<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>US_Compilation_Checklist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>49cfa055-2b09-4c3f-a722-9f6c523de635</testSuiteGuid>
   <testCaseLink>
      <guid>3b170662-61f8-4311-a399-c354857a6ac9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/USA_Compilation_Checklists/1.Copy_CompChecklists_From_Master_To_Firm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>065c70c0-12e0-4b0a-a147-c99516a0f47e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12042547-a202-41d4-a0f6-303c7c64caa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d5ac219-e351-4ec1-8ad8-c12490c63b23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35e529a0-b1e1-4325-a846-436ed697193f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/USA_Compilation_Checklists/2.Add_Question_And_Category</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56454599-d07f-477f-9f8f-f6bc55e42466</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94c1c7b2-b7bd-4c21-8fd9-5960deb32f39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5065887c-1c0c-483f-b3bb-946108ded624</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec951dd2-0f55-42ba-a501-f45e9d84e18c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/USA_Compilation_Checklists/3.Checklist_Kebab_Options</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>333ae4fb-6434-4c19-834f-135bfe4de129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d852e9e-c166-4581-80e8-075278679958</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15850f5e-1120-4751-82fa-c67a991c3f03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b3d3bb25-da4e-4420-b4b5-522b833ec23e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/USA_Compilation_Checklists/4.Map_Checklist_Engagement_Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61a2b5d2-0154-4725-a15c-dfa20bad59e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c651b2d2-ca18-4147-88fe-a8da67166497</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c1bdcea-159d-4127-9957-6a4917cc44cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23df4e15-fd0b-44cc-a58e-5e4e7d907ee0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/USA_Compilation_Checklists/5.Create_Engagement_Compilation_default_template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2ebbf8b-b096-495f-a96d-1587d05c3ace</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5091f2c5-abed-46c2-bf9b-a4d7340f8ab9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09b9c416-c5bf-4a39-918d-585125892944</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>99ed77e2-377f-4226-95d6-45d0d5fd49f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/USA_Compilation_Checklists/6.Tax_Checklist_Inside_Engagement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba92d4ef-4069-422c-91d0-dcb331c120c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f027481-d363-47c9-aa23-111b241a063f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc3be7b-9aed-4893-9313-bfc48ca4737e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
