<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>US_Review_Checklist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bd37e5ff-7824-4449-a667-e14000c45f1e</testSuiteGuid>
   <testCaseLink>
      <guid>a977adcf-3712-4be7-97bc-c6ac1e1d0c22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/US_Review_Checklist/1.Copy_ReviewChecklists_From_Master_To_Firm - USA</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa2a0376-9e56-4850-801d-09eec550a7d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7684f3e3-f366-4040-899a-c07664fd4d48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c00709c1-4813-4d7c-9b42-c214e7004d88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00e5462b-1bb1-4ca4-ad01-67c60e4e54bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/US_Review_Checklist/2.Add_Question_And_Category_Review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e6edb2f-c334-4457-966c-a697e6c80447</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15cd0420-4fb3-4a50-baa7-e2f6bdaa43c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd632304-1e45-4b65-a7ea-4accc494e599</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c283e46-b865-43a0-922c-dbb863230a09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/US_Review_Checklist/3.Checklist_Kebab_Options_Review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50457d23-5641-4433-911c-5b3030fd20ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3731c6a-414b-4d14-867a-a68f0bbea8e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2573ddc8-f2c9-4f02-a533-f67a8758bd45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>68b6bb62-710a-4b07-8bc6-479f1292dc7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/US_Review_Checklist/4.Map_Checklist_Engagement_Template</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>764e78c8-bec8-49f0-980d-e1ae9494e265</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e1f7674-760d-4204-8671-49f828a62c8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b63325ce-6879-44be-94cf-916815cce249</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d44794c-a795-4cc5-8142-6f864de39ad1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Updated_UAT/Checklists/US_Review_Checklist/5.Create_Engagement_Review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7deb6b9f-2344-4fdd-af25-f2b32d549cb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d80bac9-26ff-4d55-839d-cb3f7d8e73cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48a0593e-01f9-40d5-baea-21d31f7682fc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
