<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Added_Ref</name>
   <tag></tag>
   <elementGuidId>64f62bf1-c2d2-40ca-b718-3e18fb0dda45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//td/button)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@mat-ripple-loader-class-name='mat-mdc-button-ripple']//span//span//span[contains(text(),'A-3')]</value>
      <webElementGuid>77df93e6-a45e-495c-83bb-5059b2207e63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
