<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tax_Checklist</name>
   <tag></tag>
   <elementGuidId>30397136-c56c-40f8-8156-2b00149c9ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-expansion-panel[1]//div[1]//div[1]//mat-list[1]//mat-list-item[1]//span[1]//span[1]//a[1]//p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
